### ISSUE TITLE
Any plans to get this upstream to 'necolas/normalize.css' ?

### ISSUE THREAD

**Issue by iemejia** [kennethormandy/normalize-opentype.css#27]
Hello,

Great work, Do you have any plans (or discussions) to get some (or all) of your changes as part of the upstream 'normalize' project ? It makes sense doesn't it ?

Thanks for the nice defaults.

**Comment by briankoser** [comment]
See https://github.com/necolas/normalize.css/issues/343

**Comment by kennethormandy** [comment]
Thanks for your interest in the project, and @briankoser for providing the answer.

I carefully developed this project to make merging it into Normalize.css possible—the testing framework, code, and comment style all referenced the original project. But I was pretty sure it wouldn’t get merged, which is why I didn’t do it as just a pull request from the beginning.

Necolas kindly gave it a try, but wasn’t interested in merging it, which is a totally fair response—it does go beyond the scope of browser defaults and well into typographic conventions.

I will hopefully be doing another pass on the whole thing in the near future, with some tests I can automate. Any changes at this point are likely to move further away from having it merged, but I think that’s okay.

Thanks for opening an issue!
